---
title: "DCLEAR : Distance based Cell LinEAge Reconstruction"
date: "`r Sys.Date()`"
author: "Il-Youp Kwak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DCLEAR : Distance based Cell LinEAge Reconstruction}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r knitr_options, echo=FALSE, results=FALSE}
library(knitr)
opts_chunk$set(fig.width = 12)
```


## What is it?


## How to use it?


### Simulation data generation


```{r loading, include=FALSE}
library(DCLEAR)
```

```{r loading2}
#' set.seed(1)
#' mu_d1 = c( 30, 20, 10, 5, 5, 1, 0.01, 0.001)
#' mu_d1 = mu_d1/sum(mu_d1)
#' simn = 100 # number of cell samples
#' m = 200  ## number of targets
#' sD = sim_seqdata(sim_n = simn, m = m, mu_d = 0.03, d = 12, n_s = length(mu_d1), outcome_prob = mu_d1, p_d = 0.005 )
#' x = sD$seqs; y = sD$tree
#' ## RF score with hamming distance
#' sD$seqs %>% dist.hamming()  %>% NJ() %>% RF.dist(y, normalize = TRUE)
#' ## RF score with weighted hamming
#' InfoW = -log(mu_d1)
#' InfoW[1:2] = 1
#' InfoW[3:7] = 4.5
#' sD$seqs %>% WH(InfoW) %>% NJ() %>% RF.dist(y, normalize = TRUE)
#' ## RF score with weighted hamming, cosidering dropout situation
#' nfoW = -log(mu_d1)
#' InfoW[1] = 1
#' InfoW[2] = 12
#' InfoW[3:7] = 3
#' sD$seqs %>% WH(InfoW, dropout=TRUE) %>% NJ() %>% RF.dist(y, normalize = TRUE)

```


## Distance estimation using hamming 

## Problems

## Ideas

## Tree construction

